# Build stage
FROM node:24-alpine AS build
WORKDIR /app

COPY package*.json ./
#It installs dependencies exactly from package-lock.json.
RUN npm ci

COPY . .

# Build-time env for Vite
ARG VITE_BACKEND_URL
ARG VITE_RAZOR_PAY_ID
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_RAZOR_PAY_ID=$VITE_RAZOR_PAY_ID

RUN npm run build

# Nginx stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
